# Generated by Django 2.2.7 on 2020-10-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.CharField(max_length=124, verbose_name='IP Адрес')),
                ('mask', models.ImageField(upload_to='masks/', verbose_name='Маска')),
                ('city', models.PositiveSmallIntegerField(choices=[(0, 'Москва'), (1, 'Питер'), (2, 'Нижний')], default=0, verbose_name='Город')),
                ('adress', models.CharField(default='', max_length=256, verbose_name='Адрес')),
                ('open_link', models.CharField(max_length=124, verbose_name='Ссылка на открытие')),
                ('active', models.BooleanField(default=False, help_text='Считываются ли данные при работе программы', verbose_name='Активна')),
                ('seconds', models.PositiveSmallIntegerField(default=1, help_text='При установке параметра учитывать             частоту траффика на конкртеном шлагбауме', verbose_name='Частота считывания (секунд)')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Полное изображение')),
                ('car', models.ImageField(upload_to='', verbose_name='Само авто')),
                ('timestamp', models.CharField(editable=False, max_length=256, verbose_name='Информация')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.Camera', verbose_name='Камера')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
